import { FaExchangeAlt, FaLeaf } from "react-icons/fa";

import Button from "../components/button";
import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-900">
      <Head>
        <title>Enchanted Rose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="mb-8">
          <img src="/assets/rose.jpg" className="w-48 rounded-lg" />
        </div>
        <h1 className="text-white text-4xl font-semibold leading-loose">
          Enchanted Rose
        </h1>

        <div className="mt-8 flex flex-row gap-12">
          <div>
            <Button iconObj={FaLeaf} label="Drop 1" />
          </div>
          <div>
            <Button iconObj={FaLeaf} label="Drop 2" />
          </div>
          <div>
            <Button iconObj={FaLeaf} label="Drop 3" />
          </div>
          <div>
            <Button iconObj={FaLeaf} label="Drop 4" />
          </div>
          <div>
            <Button iconObj={FaExchangeAlt} label="Test connectivity" />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
